CREATE DATABASE BDPOLICIA
GO
USE BDPOLICIA
DROP TABLE ENTIDADBANCARIA
SELECT * FROM 

CREATE TABLE ENTIDADBANCARIA
(
	IdEntidadBancaria INT PRIMARY KEY,
	Direccion VARCHAR(10)
)

CREATE TABLE SUCURSAL
(
	IdSUCURSAL INT PRIMARY KEY,
	Direccion VARCHAR(10),
	NroEmpleado TINYINT,
	IdEntidadBancaria INT,
	FOREIGN KEY (IdEntidadBancaria) REFERENCES ENTIDADBANCARIA(IdEntidadBancaria)
	)

CREATE TABLE VIGILANTE
(
	IdVigilante INT PRIMARY KEY,
	NombreVig VARCHAR (20),
	Edad TINYINT,
	)

CREATE TABLE SUCURSAL_VIGILANTE
(
	IdSucVig INT PRIMARY KEY,
	IdVigilante INT,
	IdSucursal INT,
	fecha DATE,
	arma VARCHAR(20),
	FOREIGN KEY (IdVigilante) REFERENCES VIGILANTE (IdVigilante),
	FOREIGN KEY (IdSucursal) REFERENCES SUCURSAL (IdSucursal)
	)

CREATE TABLE ATRACOS
(
	IdAtracos INT PRIMARY KEY,
	IdAtracador INT,
	IdSucursal INT,
	FechaAtraco DATE,
	FOREIGN KEY (IdAtracador) REFERENCES ATRACADOR (IdAtracador),
	FOREIGN KEY (IdSucursal) REFERENCES SUCURSAL (IdSucursal)
	)

CREATE TABLE ATRACADOR 
(
	IdAtracador INT PRIMARY KEY,
	IdBanda INT,
	NombreAtracador VARCHAR (20),
	FOREIGN KEY (IdBanda) REFERENCES BANDA (IdBanda)
	)

CREATE TABLE BANDA
(
	IdBanda INT PRIMARY KEY,
	NroIntregantes TINYINT
	)

CREATE TABLE AtracadorJuez
(
	IdAtracadorJuez INT PRIMARY KEY,
	IdAtracador INT,
	IdJuez INT,
	Condenado VARCHAR(20),
	AñosCondena DATE,
	FOREIGN KEY (IdAtracador) REFERENCES ATRACADOR(IdAtracador),
	FOREIGN KEY (IdJuez) REFERENCES JUEZ (IdJuez)
	)

CREATE TABLE JUEZ
(
	IdJuez INT PRIMARY KEY,
	AñosServicio DATE
)